### ISSUE TITLE
How to set the Vue MDL color in a production environment

### ISSUE THREAD

**Issue by poppop0911** [posva/vue-mdl#108]
How to set the Vue MDL color in a production environment.

I hope to be able to set the color more easily.
May be described it in the documentation.

**Comment by posva** [comment]
The easiest way is to use a CDN version: https://getmdl.io/customize/index.html
Otherwise, it can be achieved by loading the original `scss` as in the docs: https://github.com/posva/vue-mdl/blob/develop/doc/src/style/mdl.scss

I found that way by trying but I agree that they could have put that up in the documentation.
