### ISSUE TITLE
Outdated documentation for MdlButton

### ISSUE THREAD

**Issue by SEIAROTg** [posva/vue-mdl#51]
The usage of icon property of MdlButton has been changed since [this commit](https://github.com/posva/vue-mdl/commit/5753424acfe95cee59a31fcb9f8715d49d6d8f75). In newer version the code shown in the documentation does not work correctly.

**The code in documentation:**

``` html
<mdl-button icon>
  <i class="material-icons">star</i>
</mdl-button>
```

**The new usage:**

``` html
<mdl-button icon="star">
</mdl-button>
```

However, simply changing this may cause documentation works incorrectly and upgrading the VueMdl that the documentation uses may lead to other problems. Hope you could check the changes globally and update the documentation.

**Comment by posva** [comment]
Oh, thank you very much @SEIAROTg !
I'll check it this evening

**Comment by posva** [comment]
I took a look and I'd like to make it more consistent with `fab` and `mini-fab` props. Putting in the `i.material-icons` let you use another icon library so I prefer keeping that it is more flexible.
I prefer not to keep the `icon="star"` syntax to make it easier but I'm not sure about this: I'm not sure if using `icon="star"` combined with `icon` + `i.material-icons star` is intuitive enough. Using one form only makes it much more clear that you can override the icon component. Otherwise that's not as clear

**Comment by SEIAROTg** [comment]
Maybe the two syntax could both be kept. But the problem now is that if you use `icon` + `i.material-icon` syntax, the button will be shown in rectangular style instead of round style as it should be. 

```coffee
computed:
 cssClasses: ->
   'mdl-button--icon': @icon
   'mdl-button--accent': @accent
   'mdl-button--primary': @primary
   'mdl-button--mini-fab': @miniFab
   'mdl-button--fab': @fab or @miniFab
   'mdl-button--raised': @raised
   'mdl-button--colored': @colored
```

Here, since the type of the prop `icon` is by default String, simply using `<mdl-button icon>` will make it be treated as empty string, which is then converted into false in class list.

**Comment by posva** [comment]
Actually, I have a mixin that sets the `icon` variable to `true` if it's defined that way.
Anyways I'll fix this and update the doc

**Comment by dsl101** [comment]
I've just started converting a Vue / MDL project over to use vue-mdl, and was caught out by this for a menu. This code works:

    <mdl-button id="projectMenu" icon="more_vert"></mdl-button>

but this (from the docs) doesn't:

    <mdl-button id="projectMenu" icon>
      <i class="material-icons">more_vert</i>
    </mdl-button>

the latter producing a square-backed icon in the wrong colour. I guess this is pretty close to what @SEIAROTg  put in the original issue, but I couldn't follow the whole of the rest of this to figure out what it _should_ be. And the docs do still need updating I guess?

Peronally I like the first syntax so I hope that it can stay :)
Tx

**Comment by posva** [comment]
I fixed this on the v1 branch. The docs are not ready yet. I'll publish the once they're finished

**Comment by tralves** [comment]
Is it just me, or with Vue 2.0 you need to register the events with `@click.native` instead of just `@click`? It sort of makes sense, according to the [Vue 2.0 doc](https://vuejs.org/v2/guide/components.html#Using-v-on-with-Custom-Events).

If that's the case, I think the docs should mention this. It may save someone else some time.

**Comment by posva** [comment]
@tralves The docs are still for version v0.x of vue-mdl not for v1.x. This wasn't necessary in Vue 1.
I'm working on updating them but it takes quite a lot of time

**Comment by tralves** [comment]
@posva I know :) It was just a small reminder. Thanks!

**Comment by piotros** [comment]
@tralves you saved me a lot of time. Thank you! :smile:
