### ISSUE TITLE
[1.0.0-alpha.1]Module build failed

### ISSUE THREAD

**Issue by goldfinger43** [posva/vue-mdl#70]
Hey,

i get the following error if i compile the new version with webpack.

ERROR in ./~/vue-mdl/dist/vue-mdl.js
Module build failed: SyntaxError: 'with' in strict mode (846:36)

hope you can help

best regards

**Comment by posva** [comment]
You seem to have strict mode activated somewhere. Make sure you're using Vue 2
Did you use any boilerplate?

**Comment by goldfinger43** [comment]
I am using laravel with vue 2
looks like vue has strict mode activated

my bootstrap.js looks like this:


window.Vue = require('vue');

/**
 *	Vue Material Components
 */
import VueMdl from 'vue-mdl';
Vue.use(VueMdl);

**Comment by posva** [comment]
I've never used Laravel, does this help? https://github.com/marcosmoura/vue-material/issues/33

Otherwise, you can import from `vue-mdl/src/vue-mdl.js` and make sure to include the jade/pug loader (some components are still in jade). This will compile vue-mdl though, so it'd take more time during your development process and I discourage it.

**Comment by luukholleman** [comment]
I'm using laravel with this and it loads fine.

This is my gulpfile:

```
var elixir = require('laravel-elixir');
var path = require('path');

require('laravel-elixir-vue-2');

elixir(function(mix) {
    mix.sass('app.scss')
        .webpack('app.js', null, null, {
            resolve: {
                modules: [
                    path.resolve(__dirname, 'vendor/laravel/spark/resources/assets/js'),
                    'node_modules'
                ],
                alias: {vue: 'vue/dist/vue.js'}
            }
        })
        .......;
});
```

**Comment by delueg** [comment]
I have a similar problem. Since using vue-mdl@next. (I didn't use vue-mdl V1).

`[Laravel Elixir] Browserify Failed!: Cannot find module '!!./../node_modules/css-loader/index.js!./../node_modules/vue-loader/lib/style-rewriter.js?id=data-v-f1faa888!./../node_modules/vue-loader/lib/selector.js?type=styles&index=0!./dialog.vue' from '/Users/svendelueg/Development/...../node_modules/vue-mdl/dist'`

**Comment by goldfinger43** [comment]
@posva the link to vue-material helped me. Had to switch my package.json to the original one from laravel. i messed up somewhere.

ty for help

**Comment by posva** [comment]
Glad it helps. It would be great to add some help to the Readme for elixir users but I cannot do it myself. So if anyone could bring some clarity for others, I'll be grateful 😄
