### ISSUE TITLE
Keyboard covers text input area on mobile

### ISSUE THREAD

**Issue by gedw99** [posva/vue-mdl#91]
This is a common problem.

I think that is a way to detect it. I remember reading about the fix a few weeks ago.

It would make this much more usable

**Comment by posva** [comment]
I googled it and found about using ids although I haven't tested it and the jsbin doesn't work http://stackoverflow.com/questions/18110852/input-textbox-hidden-behind-keyboard-on-android-chrome

Anyway, this belongs to mdl itself more than vue-mdl and can be achieved on user land easily so there's no point in automatically doing so because not everyone wants the page to scroll automatically
